<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxSByR9\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxSByR9/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxSByR9.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxSByR9\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxSByR9\App_KernelDevDebugContainer([
    'container.build_hash' => 'SxSByR9',
    'container.build_id' => '842b600e',
    'container.build_time' => 1665053833,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxSByR9');
