<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSxnkcAS\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSxnkcAS/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSxnkcAS.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSxnkcAS\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSxnkcAS\App_KernelDevDebugContainer([
    'container.build_hash' => 'SxnkcAS',
    'container.build_id' => 'c7046b3b',
    'container.build_time' => 1594002356,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSxnkcAS');
