<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'chambre' => [[], ['_controller' => 'App\\Controller\\ChambreController::index'], [], [['text', '/chambre']], [], []],
    'createChambre' => [[], ['_controller' => 'App\\Controller\\ChambreController::createChambre'], [], [['text', '/CreateChambre']], [], []],
    'AddEtudiant' => [[], ['_controller' => 'App\\Controller\\ChambreController::AddEtudiant'], [], [['text', '/AddEtudiant']], [], []],
    'home' => [[], ['_controller' => 'App\\Controller\\ChambreController::home'], [], [['text', '/']], [], []],
    'allocation' => [[], ['_controller' => 'App\\Controller\\ChambreController::allocation'], [], [['text', '/allocation']], [], []],
];
